# version: '3.8'
services:
  user-service:
    image: user-service:0.0.1
    container_name: users
    ports:
      - "3003:3003"
    env_file:
      - .env
    networks:
      - service_network
    deploy:
      resources:
        limits:
          memory: 512M  #Maximo de memoria permitido
        reservations:
          memory: 256M
  
  email-service:
    image: email-service:0.0.4
    container_name: email
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - service_network
    deploy:
      resources:
        limits:
          memory: 512M  #Maximo de memoria permitido
        reservations:
          memory: 256M
    
  esb-service:
    image: esb-service:0.0.1
    container_name: esb-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - service_network
    deploy:
      resources:
        limits:
          memory: 512M  #Maximo de memoria permitido
        reservations:
          memory: 256M
      
networks:
  service_network:
    external: true



