# version: '3.8'
services:
  user-service:
    image: user-service:0.0.1
    container_name: users
    ports:
      - "3010:3000"
    env_file:
      - .env
    networks:
      - service_network
      
networks:
  service_network:
    external: true



